### ISSUE TITLE
vultr.DnsRecord - MX and CNAME records

### ISSUE THREAD

**Issue by dR3b** [dirien/pulumi-vultr#141]
Hi,

when I created a new domain via "vultr.DnsRecord", it automatically adds a `MX` and a `CNAME` record. Why? How can I delete them?

```
import pulumi
import ediri_vultr as vultr

my_domain = vultr.DnsDomain("foobar", domain="foobar.foo", ip="1.2.3.4")
```

```
A     1.2.3.4         300
CNAME * foobar.foo    300
MX    foobar.foo      300 10
NS    ns1.vultr.com   300
NS    ns2.vultr.com   300
```
Thanks

**Comment by dirien** [comment]
Hey @dR3b, 

according to the docs, you should create the `DnsDomain` resource without the `IP` address no records will be created.

And the. you can use `DnsRecord` to create the records!

**Comment by dR3b** [comment]
Thanks! I only saw the example on this page: https://www.pulumi.com/registry/packages/vultr/api-docs/dnsdomain/

```
import pulumi
import ediri_vultr as vultr

my_domain = vultr.DnsDomain("myDomain",
    domain="domain.com",
    ip="66.42.94.227")
```

**Comment by dirien** [comment]
yeah, that's the official example from the Vultr TF provider! I had to check the Vultr API docs for more details! 🙈
