### ISSUE TITLE
In-place upgrade attempted on incompatible server type

### ISSUE THREAD

**Issue by SubstructureDek** [dirien/pulumi-vultr#150]
[Vultr docs specify](https://www.vultr.com/docs/how-to-upgrade-your-plan-without-reinstalling/) that in-place upgrades are not supported when changing server types. However if you change an instance type using the Python interface from a `vc2` type plan to a `vhp` type plan, Pulumi attempts to modify the server type in-place, resulting in an error from Vultr: 

`"{\"error\":\"Unable to upgrade plan: This plan is not an upgrade.\",\"status\":500}"`

To reproduce: create a Pulumi configuration with an plan ID of `vc2-1c-1gb`, deploy, change plan ID to `vhp-1c-1gb-amd`, attempt redeploy.

I have only tested the specific scenario described above, and only using the Pulumi Python interface.

**Comment by dirien** [comment]
Hey @SubstructureDek,

can you try a `deleteBeforeReplace`

https://www.pulumi.com/docs/concepts/options/deletebeforereplace/
