### ISSUE TITLE
bug: `vultr:apiKey` is not a valid configuration key for the vultr provider

### ISSUE THREAD

**Issue by domdomegg** [dirien/pulumi-vultr#423]
This appears to be a regression between 2.19.0 and 2.21.1.

It previously worked to set a config key `vultr:apiKey`, including as a secret, to set the vultr configuration. But some change has made this break between these versions.

You can see a diff (just version change) and failure logs here: https://github.com/bluedotimpact/bluedot/actions/runs/11573149652/job/32214753863

**Comment by domdomegg** [comment]
After some testing, I found this is a regression between 2.20.1 and 2.21.1.

2.21.0 fails with some other error, which I think might be related to #361?

**Comment by domdomegg** [comment]
Possibly relating to bumping the terraform version provider: https://github.com/dirien/pulumi-vultr/pull/362

Which included this change: https://github.com/pulumi/pulumi-terraform-bridge/pull/1663

**Comment by mococa** [comment]
can confirm, using this version on my node pulumi app fixed for now:
```
"@ediri/vultr": "2.20.1"
```

**Comment by dirien** [comment]
Hey @domdomegg and @mococa,

Sorry for the issue. Let me check what could be the reason for this.

**Comment by dirien** [comment]
Created an issue: https://github.com/pulumi/pulumi-terraform-bridge/issues/2582

**Comment by lekhanhtoan37** [comment]
Any update?. Still bug

**Comment by dirien** [comment]
Hey @lekhanhtoan37,@domdomegg, and @mococa,

Please use/upgrade to version `2.22.1` of the provider. Sorry for the delay.

**Comment by domdomegg** [comment]
No worries about the delay - appreciate you're maintaining this voluntarily. Thanks for an awesome library and for fixing this :)
